# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.17.0

pipelines:
  branches:
    develop:
      - parallel:
          # - step:
              # name: Build react project
              # caches:
                # - node
              # script: # Modify the commands below to build your repository.
                # - yarn install
                ## - npm test
                ## - npm run build
                ## - tar czfv application.tgz build/
              ## artifacts:
                ## - application.tgz
          - step:
              name: Unit testing
              script:
                - yarn install
                - yarn test
      - step:
          name: Git merge and deploy
          caches:
            - node
          script:
            - yarn install
            # - npm run build
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git +HEAD:master
      # - step:
          # name: Deploy to production
          # deployment: production
          # script:
            # - pipe: atlassian/heroku-deploy:0.1.1
              # variables:
                # HEROKU_API_KEY: $HEROKU_API_KEY
                # HEROKU_APP_NAME: $HEROKU_APP_NAME
                # ZIP_FILE: "application.tgz"
      # - step:
          # name: Percy snapshots
          # script:
            # - apt-get update && apt-get install -yq libgconf-2-4
            # - >
              # apt-get update && apt-get install -y wget --no-install-recommends && \
              # wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
              # sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
              # apt-get update && \
              # apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
              # Dont worry about cleaning up files left after installation.
            # - yarn install
            # - yarn percy