# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Build project
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm build
          - npm test
    - step:
        name: Create artifact
        script:
          - tar czvf $ZIP_FILE public/
        artifacts:
          - $ZIP_FILE
    - step:
        name: Deploy to production
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: $ZIP_FILE